//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public int Studentid { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Session_Name { get; set; }
        public string Answers { get; set; }
        public Nullable<int> Surveyid { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
