//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyDetail()
        {
            this.Siblings = new HashSet<Sibling>();
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public int Familyid { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Guardian_Name { get; set; }
        public string Father_Profession { get; set; }
        public string Mother_Profession { get; set; }
        public Nullable<int> No_of_Working_Days_Father { get; set; }
        public Nullable<int> No_Of_Working_Days_Mother { get; set; }
        public string Father_Working_Days { get; set; }
        public string Mother_WOrking_Days { get; set; }
        public Nullable<int> Family_Income { get; set; }
        public Nullable<int> Total_Children { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sibling> Siblings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
    }
}
