//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sibling
    {
        public Nullable<int> Familyid { get; set; }
        public Nullable<int> studentid { get; set; }
        public int siblingid { get; set; }
        public string Name { get; set; }
        public string Marital_Status { get; set; }
        public string Profession { get; set; }
        public Nullable<int> DaysWOrdedPerMonth { get; set; }
        public string Gender { get; set; }
    
        public virtual FamilyDetail FamilyDetail { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
