//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamDetail
    {
        public int Teamid { get; set; }
        public string TeamName { get; set; }
        public string Captain { get; set; }
        public Nullable<bool> is_enabled { get; set; }
    }
}
