//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueRankingForm
    {
        public string Label { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string PlayerName { get; set; }
        public string Skill { get; set; }
        public int entityID { get; set; }
    }
}
