//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YuwaEntities : DbContext
    {
        public YuwaEntities()
            : base("name=YuwaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassDetail> ClassDetails { get; set; }
        public virtual DbSet<CoachDetail> CoachDetails { get; set; }
        public virtual DbSet<FamilyDetail> FamilyDetails { get; set; }
        public virtual DbSet<Sibling> Siblings { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
        public virtual DbSet<SurveyList> SurveyLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeamDetail> TeamDetails { get; set; }
        public virtual DbSet<ValueRankingForm> ValueRankingForms { get; set; }
        public virtual DbSet<Yw_features> Yw_features { get; set; }
        public virtual DbSet<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual DbSet<CoachAttendance> CoachAttendances { get; set; }
        public virtual DbSet<ListOfHoliday> ListOfHolidays { get; set; }
        public virtual DbSet<SurveyQuestioniarre> SurveyQuestioniarres { get; set; }
    }
}
