//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuwamt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yw_features
    {
        public int featureid { get; set; }
        public string Feature_Name { get; set; }
        public string Feature_pic { get; set; }
        public string Feature_Description { get; set; }
        public Nullable<bool> is_enable { get; set; }
    }
}
